[pytest]
addopts = -s --alluredir=report --strict-markers --strict-config -ra --tb=short
pythonpath = .
testpaths = testcase
markers =
    smoke: 冒烟测试
    regression: 回归测试
    concurrency: 并发测试
    integration: 集成测试
log_cli = true
log_cli_level = INFO
